export type CategoryName = "Laptops" | "Smartphones" | "Tablets" | "Accessories" | "Smartwatches";

export type Product = {
  id: string;
  name: string;
  brand: string;
  category: CategoryName;
  price: number;
  originalPrice: number;
  discount: number;
  rating: number;
  reviewCount: number;
  description: string;
  features: string[];
  images: string[];
  colors: string[];
  storageOptions: string[];
  stock: number;
  badge?: string;
};

export const categories: { name: CategoryName; slug: string; description: string; count: number }[] = [
  { name: "Laptops", slug: "laptops", description: "Premium laptops for work, study, and play.", count: 11 },
  { name: "Smartphones", slug: "smartphones", description: "Latest smartphones with cutting-edge performance.", count: 13 },
  { name: "Tablets", slug: "tablets", description: "Portable power for creativity and entertainment.", count: 7 },
  { name: "Accessories", slug: "accessories", description: "Boost your setup with modern essentials.", count: 16 },
  { name: "Smartwatches", slug: "smartwatches", description: "Track fitness and stay connected on the go.", count: 8 },
];

export const products: Product[] = [
  {
    id: "macbook-air-m2",
    name: "MacBook Air M2",
    brand: "Apple",
    category: "Laptops",
    price: 1199,
    originalPrice: 1399,
    discount: 14,
    rating: 4.9,
    reviewCount: 321,
    description: "Ultra-lightweight laptop with an all-day battery, stunning Retina display, and the performance to handle productivity, creativity, and entertainment effortlessly.",
    features: ["13.6-inch Liquid Retina display", "Apple M2 chip", "Up to 18 hours battery life", "Fanless design", "Backlit keyboard"],
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Silver", "Midnight", "Starlight", "Space Gray"],
    storageOptions: ["256GB", "512GB", "1TB"],
    stock: 18,
    badge: "Best Seller",
  },
  {
    id: "dell-xps-13",
    name: "Dell XPS 13",
    brand: "Dell",
    category: "Laptops",
    price: 999,
    originalPrice: 1199,
    discount: 17,
    rating: 4.8,
    reviewCount: 244,
    description: "A premium ultrabook with a near-borderless InfinityEdge display and cutting-edge Intel performance for work and travel.",
    features: ["13.4-inch FHD+ display", "Intel Core i7", "16GB RAM", "512GB SSD", "Windows 11 Pro"],
    images: [
      "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1504703395950-b89145a5425b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Platinum Silver", "Black"],
    storageOptions: ["512GB", "1TB"],
    stock: 14,
  },
  {
    id: "hp-spectre-x360",
    name: "HP Spectre x360",
    brand: "HP",
    category: "Laptops",
    price: 1099,
    originalPrice: 1299,
    discount: 15,
    rating: 4.7,
    reviewCount: 193,
    description: "Convertible premium laptop that effortlessly transitions between laptop, tablet, and creative workstation modes.",
    features: ["14-inch 2.8K OLED", "Intel Evo Platform", "16GB RAM", "1TB SSD", "360° hinge"],
    images: [
      "https://images.unsplash.com/photo-1551808525-51a94da548ce?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Nightfall Black", "Poseidon Blue"],
    storageOptions: ["512GB", "1TB"],
    stock: 20,
  },
  {
    id: "asus-zenbook-14",
    name: "ASUS ZenBook 14",
    brand: "ASUS",
    category: "Laptops",
    price: 949,
    originalPrice: 1099,
    discount: 14,
    rating: 4.6,
    reviewCount: 162,
    description: "Sleek ultrabook with a compact footprint and strong everyday performance for professionals and students.",
    features: ["14-inch OLED display", "AMD Ryzen 7", "16GB RAM", "1TB SSD", "USB-C fast charge"],
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541534401786-2077eed87a74?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Ponder Blue", "Gray"],
    storageOptions: ["512GB", "1TB"],
    stock: 26,
  },
  {
    id: "lenovo-thinkpad-x1",
    name: "Lenovo ThinkPad X1",
    brand: "Lenovo",
    category: "Laptops",
    price: 1349,
    originalPrice: 1549,
    discount: 13,
    rating: 4.7,
    reviewCount: 130,
    description: "Built for business productivity with legendary keyboard comfort, enterprise-grade durability, and secure performance.",
    features: ["14-inch UHD display", "Intel Core i7", "32GB RAM", "1TB SSD", "ThinkShield security"],
    images: [
      "https://images.unsplash.com/photo-1521543381607-4fddd1d76c8b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Graphite"],
    storageOptions: ["512GB", "1TB"],
    stock: 11,
  },
  {
    id: "msi-gaming-laptop",
    name: "MSI Raider GE78",
    brand: "MSI",
    category: "Laptops",
    price: 1699,
    originalPrice: 1999,
    discount: 15,
    rating: 4.8,
    reviewCount: 188,
    description: "Performance-first gaming laptop with high-refresh display, advanced cooling, and immersive visuals for serious players.",
    features: ["17.3-inch QHD+ display", "RTX 4080", "32GB RAM", "2TB SSD", "144Hz refresh"],
    images: [
      "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Titanium"],
    storageOptions: ["1TB", "2TB"],
    stock: 9,
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "Smartphones",
    price: 999,
    originalPrice: 1099,
    discount: 9,
    rating: 4.9,
    reviewCount: 431,
    description: "A titanium-framed flagship with exceptional camera power, a blazing-fast chip, and all-day performance.",
    features: ["6.1-inch Super Retina XDR", "A17 Pro chip", "Pro camera system", "USB-C connectivity", "Dynamic Island"],
    images: [
      "https://images.unsplash.com/photo-1671107965015-0f547e8e1fe3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Natural Titanium", "Blue Titanium", "White Titanium"],
    storageOptions: ["128GB", "256GB", "512GB", "1TB"],
    stock: 35,
    badge: "Hot Deal",
  },
  {
    id: "samsung-galaxy-s24",
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    category: "Smartphones",
    price: 829,
    originalPrice: 949,
    discount: 13,
    rating: 4.8,
    reviewCount: 275,
    description: "A powerful AI-enhanced smartphone with a brilliant display and versatile camera system built for every day.",
    features: ["6.2-inch AMOLED display", "Snapdragon 8 Gen 3", "50MP camera", "AI tools", "Fast wireless charging"],
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Onyx Black", "Marble Gray", "Violet"],
    storageOptions: ["128GB", "256GB", "512GB"],
    stock: 42,
  },
  {
    id: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "Smartphones",
    price: 799,
    originalPrice: 899,
    discount: 11,
    rating: 4.7,
    reviewCount: 214,
    description: "A smooth and fast flagship with flagship-level cameras, immersive visuals, and fluid performance.",
    features: ["6.8-inch AMOLED display", "Snapdragon 8 Gen 3", "120Hz refresh rate", "Triple camera system", "Ultra-fast charging"],
    images: [
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Fluorite Black", "Flowing Silver"],
    storageOptions: ["256GB", "512GB"],
    stock: 29,
  },
  {
    id: "google-pixel-9",
    name: "Google Pixel 9",
    brand: "Google",
    category: "Smartphones",
    price: 749,
    originalPrice: 899,
    discount: 17,
    rating: 4.6,
    reviewCount: 183,
    description: "Built around AI photography and seamless Android integration, designed to make everyday moments feel effortless.",
    features: ["6.3-inch display", "Tensor G4", "Advanced AI camera", "7 years updates", "Wireless charging"],
    images: [
      "https://images.unsplash.com/photo-1601784551446-20c9e07d2c4e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1521311863870-7e1b10d6bf0c?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Obsidian", "Porcelain"],
    storageOptions: ["128GB", "256GB"],
    stock: 32,
  },
  {
    id: "nothing-phone-2",
    name: "Nothing Phone 2",
    brand: "Nothing",
    category: "Smartphones",
    price: 699,
    originalPrice: 799,
    discount: 13,
    rating: 4.5,
    reviewCount: 121,
    description: "A distinctive design and clean Android experience with sustainable materials and good everyday performance.",
    features: ["6.7-inch AMOLED", "Glyph interface", "Dual rear cameras", "Snapdragon 8+ Gen 1", "Fast charging"],
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["White", "Black"],
    storageOptions: ["128GB", "256GB"],
    stock: 25,
  },
  {
    id: "ipad-air",
    name: "iPad Air",
    brand: "Apple",
    category: "Tablets",
    price: 599,
    originalPrice: 699,
    discount: 14,
    rating: 4.8,
    reviewCount: 270,
    description: "An ultra-portable tablet that combines an immersive display with all-day battery life and powerful creative tools.",
    features: ["10.9-inch Liquid Retina display", "M2 chip", "Apple Pencil support", "Touch ID", "USB-C"],
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1452784444945-3f883f4d2ec7?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Space Gray", "Blue", "Purple"],
    storageOptions: ["64GB", "256GB"],
    stock: 19,
  },
  {
    id: "samsung-galaxy-tab-s9",
    name: "Samsung Galaxy Tab S9",
    brand: "Samsung",
    category: "Tablets",
    price: 649,
    originalPrice: 749,
    discount: 13,
    rating: 4.7,
    reviewCount: 149,
    description: "Premium Android tablet with an immersive AMOLED display and strong productivity features for work and creativity.",
    features: ["11-inch AMOLED", "Qualcomm Snapdragon", "S Pen included", "Dual speakers", "Long battery life"],
    images: [
      "https://images.unsplash.com/photo-1589739900243-4b5d7d7a9d90?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512054502232-10a0a035d672?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Beige", "Graphite"],
    storageOptions: ["128GB", "256GB"],
    stock: 17,
  },
  {
    id: "microsoft-surface-go-4",
    name: "Microsoft Surface Go 4",
    brand: "Microsoft",
    category: "Tablets",
    price: 499,
    originalPrice: 599,
    discount: 17,
    rating: 4.4,
    reviewCount: 92,
    description: "Portable and lightweight 2-in-1 tablet with flexible productivity features for students and on-the-go creators.",
    features: ["10.5-inch touchscreen", "Intel processor", "Windows 11", "Portable design", "Keyboard compatible"],
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Platinum", "Black"],
    storageOptions: ["64GB", "128GB"],
    stock: 21,
  },
  {
    id: "airpods-pro",
    name: "AirPods Pro",
    brand: "Apple",
    category: "Accessories",
    price: 249,
    originalPrice: 299,
    discount: 17,
    rating: 4.9,
    reviewCount: 512,
    description: "Wireless earbuds with adaptive audio, active noise cancellation, and a comfortable, secure fit for all-day listening.",
    features: ["Active noise cancellation", "Adaptive audio", "USB-C charging case", "Spatial audio", "Sweat and water resistant"],
    images: [
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["White", "Black"],
    storageOptions: ["Standard"],
    stock: 48,
    badge: "Top Rated",
  },
  {
    id: "logitech-mx-master-3",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "Accessories",
    price: 99,
    originalPrice: 129,
    discount: 23,
    rating: 4.8,
    reviewCount: 359,
    description: "A premium wireless mouse for creators and professionals with exceptional precision, smooth scrolling, and multi-device control.",
    features: ["Ultra-fast scroll", "Multi-device pairing", "Quiet clicks", "Ergonomic shape", "USB-C charging"],
    images: [
      "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Graphite", "Black"],
    storageOptions: ["Standard"],
    stock: 52,
  },
  {
    id: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "Accessories",
    price: 379,
    originalPrice: 449,
    discount: 16,
    rating: 4.9,
    reviewCount: 286,
    description: "Premium noise-canceling headphones tuned for crisp audio, travel comfort, and immersive listening.",
    features: ["Industry-leading ANC", "30-hour battery", "Quick charge", "Ambient sound control", "Bluetooth multipoint"],
    images: [
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Silver"],
    storageOptions: ["Standard"],
    stock: 23,
  },
  {
    id: "belkin-usb-c-hub",
    name: "Belkin USB-C Hub",
    brand: "Belkin",
    category: "Accessories",
    price: 89,
    originalPrice: 109,
    discount: 18,
    rating: 4.6,
    reviewCount: 98,
    description: "Expand your laptop connectivity with a compact USB-C hub offering power, HDMI, and multiple USB ports.",
    features: ["4K HDMI output", "Multiple USB-A ports", "Power delivery", "Compact design", "Plug-and-play"],
    images: [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Gray"],
    storageOptions: ["Standard"],
    stock: 37,
  },
  {
    id: "apple-watch-series-9",
    name: "Apple Watch Series 9",
    brand: "Apple",
    category: "Smartwatches",
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.8,
    reviewCount: 332,
    description: "A powerful smartwatch with health insights, faster performance, and all-day battery to keep up with your routine.",
    features: ["Always-On Retina display", "GPS + Cellular", "Advanced health tracking", "Water resistant", "Fast charging"],
    images: [
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Midnight", "Starlight", "Silver"],
    storageOptions: ["41mm", "45mm"],
    stock: 40,
  },
  {
    id: "garmin-forerunner-265",
    name: "Garmin Forerunner 265",
    brand: "Garmin",
    category: "Smartwatches",
    price: 329,
    originalPrice: 399,
    discount: 18,
    rating: 4.7,
    reviewCount: 171,
    description: "Designed for runners and active lifestyles, bringing a bright display and detailed training insights to your wrist.",
    features: ["GPS + HRM", "Training readiness", "Long battery life", " AMOLED display", "Body battery"],
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Gray", "Blue"],
    storageOptions: ["42mm", "46mm"],
    stock: 34,
  },
  {
    id: "samsung-galaxy-watch-6",
    name: "Samsung Galaxy Watch 6",
    brand: "Samsung",
    category: "Smartwatches",
    price: 299,
    originalPrice: 349,
    discount: 14,
    rating: 4.6,
    reviewCount: 157,
    description: "A versatile smartwatch with smart health tracking, intuitive gestures, and a slim, premium design.",
    features: ["Advanced sleep tracking", "Body composition analysis", "Bluetooth + LTE", "Super AMOLED", "Water resistant"],
    images: [
      "https://images.unsplash.com/photo-1617043786394-f977fa12eddf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Graphite", "Silver"],
    storageOptions: ["40mm", "44mm"],
    stock: 29,
  },
  {
    id: "asus-rog-phone-8",
    name: "ASUS ROG Phone 8",
    brand: "ASUS",
    category: "Smartphones",
    price: 899,
    originalPrice: 999,
    discount: 10,
    rating: 4.7,
    reviewCount: 129,
    description: "A gamer-focused flagship with a high-refresh display, exceptional airflow, and performance tuned for competitive play.",
    features: ["6.78-inch AMOLED", "Snapdragon 8 Gen 3", "AeroActive cooling", "Dual front speakers", "Game controls"],
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Phantom Black", "Storm White"],
    storageOptions: ["256GB", "512GB"],
    stock: 18,
  },
  {
    id: "apple-mac-mini-m4",
    name: "Apple Mac mini M4",
    brand: "Apple",
    category: "Accessories",
    price: 699,
    originalPrice: 799,
    discount: 13,
    rating: 4.7,
    reviewCount: 135,
    description: "An efficient desktop mini-PC built for home offices, creative workflows, and compact setups that still demand power.",
    features: ["Compact desktop form", "M4 chip", "Thunderbolt ports", "Wi-Fi 6E", "Energy efficient"],
    images: [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Silver", "Space Gray"],
    storageOptions: ["256GB", "512GB"],
    stock: 16,
  },
  {
    id: "asus-zenbook-duo",
    name: "ASUS ZenBook Duo 14",
    brand: "ASUS",
    category: "Laptops",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    rating: 4.7,
    reviewCount: 142,
    description: "Dual-screen productivity powerhouse for multitasking, creative workflows, and efficient work-from-anywhere setups.",
    features: ["Dual 14-inch OLED displays", "Intel Core Ultra 7", "32GB RAM", "1TB SSD", "Portable dual-screen design"],
    images: [
      "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Celestial Blue", "Inkwell Gray"],
    storageOptions: ["512GB", "1TB"],
    stock: 12,
  },
  {
    id: "surface-laptop-7",
    name: "Microsoft Surface Laptop 7",
    brand: "Microsoft",
    category: "Laptops",
    price: 1199,
    originalPrice: 1399,
    discount: 14,
    rating: 4.8,
    reviewCount: 208,
    description: "A refined Copilot+ ready laptop with an ultra-light body, vivid display, and strong all-day performance.",
    features: ["13.8-inch PixelSense display", "Snapdragon X Elite", "16GB RAM", "512GB SSD", "All-day battery"],
    images: [
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541534401786-2077eed87a74?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Platinum", "Black"],
    storageOptions: ["256GB", "512GB", "1TB"],
    stock: 15,
  },
  {
    id: "samsung-fold-6",
    name: "Samsung Galaxy Z Fold 6",
    brand: "Samsung",
    category: "Smartphones",
    price: 1799,
    originalPrice: 1999,
    discount: 10,
    rating: 4.8,
    reviewCount: 224,
    description: "A foldable flagship designed for multitasking, productivity, and immersive entertainment in one premium device.",
    features: ["7.6-inch main display", "Dual hinge design", "Snapdragon 8 Gen 3", "12GB RAM", "AI camera features"],
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Silver Shadow", "Craft White"],
    storageOptions: ["256GB", "512GB", "1TB"],
    stock: 11,
  },
  {
    id: "xiaomi-14t-pro",
    name: "Xiaomi 14T Pro",
    brand: "Xiaomi",
    category: "Smartphones",
    price: 699,
    originalPrice: 799,
    discount: 13,
    rating: 4.6,
    reviewCount: 143,
    description: "A high-value flagship with strong cameras, vibrant visuals, and dependable performance at a competitive price.",
    features: ["6.67-inch AMOLED", "50MP Leica camera", "AI image enhancement", "120W charging", "Dual SIM"],
    images: [
      "https://images.unsplash.com/photo-1601784551446-20c9e07d2c4e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Blue"],
    storageOptions: ["256GB", "512GB"],
    stock: 22,
  },
  {
    id: "sony-xperia-1-vi",
    name: "Sony Xperia 1 VI",
    brand: "Sony",
    category: "Smartphones",
    price: 1299,
    originalPrice: 1449,
    discount: 10,
    rating: 4.6,
    reviewCount: 112,
    description: "A cinematic flagship for creators, delivering a pro-focused camera system and a tall, crisp display.",
    features: ["6.5-inch 4K display", "Triple camera system", "Variable telephoto lens", "Cinema pro controls", "Bravia tuning"],
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Green"],
    storageOptions: ["256GB", "512GB"],
    stock: 17,
  },
  {
    id: "ipad-pro-13",
    name: "iPad Pro 13-inch",
    brand: "Apple",
    category: "Tablets",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    rating: 4.9,
    reviewCount: 310,
    description: "A high-end creative tablet with a massive display, pro-level performance, and seamless support for Apple Pencil.",
    features: ["13-inch Ultra Retina XDR", "M4 chip", "Liquid glass design", "Apple Pencil Pro support", "Thunderbolt"],
    images: [
      "https://images.unsplash.com/photo-1452784444945-3f883f4d2ec7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Silver", "Space Black"],
    storageOptions: ["256GB", "512GB", "1TB"],
    stock: 8,
  },
  {
    id: "lenovo-tab-p12",
    name: "Lenovo Tab P12",
    brand: "Lenovo",
    category: "Tablets",
    price: 449,
    originalPrice: 549,
    discount: 18,
    rating: 4.5,
    reviewCount: 89,
    description: "A streamlined Android tablet made for streaming, reading, and light creative work on the go.",
    features: ["12.7-inch 3K display", "Octa-core processor", "Stylus support", "Quad speakers", "Long battery life"],
    images: [
      "https://images.unsplash.com/photo-1512054502232-10a0a035d672?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1589739900243-4b5d7d7a9d90?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Gray", "Blue"],
    storageOptions: ["128GB", "256GB"],
    stock: 19,
  },
  {
    id: "beats-studio-pro",
    name: "Beats Studio Pro",
    brand: "Beats",
    category: "Accessories",
    price: 349,
    originalPrice: 399,
    discount: 13,
    rating: 4.7,
    reviewCount: 197,
    description: "Wireless over-ear headphones delivering rich bass, premium comfort, and strong active noise cancellation.",
    features: ["Adaptive ANC", "Spatial audio", "Fast charging", "Soft over-ear cushions", "Bluetooth multipoint"],
    images: [
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Sandstone"],
    storageOptions: ["Standard"],
    stock: 27,
  },
  {
    id: "razer-deathadder-v3",
    name: "Razer DeathAdder V3",
    brand: "Razer",
    category: "Accessories",
    price: 69,
    originalPrice: 89,
    discount: 22,
    rating: 4.8,
    reviewCount: 242,
    description: "An esports-focused gaming mouse with ergonomic comfort, precise tracking, and durable click performance.",
    features: ["Ultra-lightweight", "Focus Pro optical sensor", "Programmable buttons", "Durable switches", "USB-C wired"],
    images: [
      "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Green"],
    storageOptions: ["Standard"],
    stock: 47,
  },
  {
    id: "google-pixel-watch-3",
    name: "Google Pixel Watch 3",
    brand: "Google",
    category: "Smartwatches",
    price: 349,
    originalPrice: 429,
    discount: 19,
    rating: 4.6,
    reviewCount: 155,
    description: "A sleek smartwatch that pairs wearable health insights with smooth Google ecosystem integration.",
    features: ["Always-on display", "Sleep tracking", "Google Assistant", "Fitness coaching", "Fast charging"],
    images: [
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Obsidian", "Porcelain"],
    storageOptions: ["41mm", "45mm"],
    stock: 26,
  },
  {
    id: "fitbit-inspire-3",
    name: "Fitbit Inspire 3",
    brand: "Fitbit",
    category: "Smartwatches",
    price: 99,
    originalPrice: 129,
    discount: 23,
    rating: 4.4,
    reviewCount: 118,
    description: "A lightweight daily wellness tracker built for sleep, activity, and easy motivation every day.",
    features: ["Sleep score", "Heart rate tracking", "Fitness reminders", "Water resistant", "Up to 10 days battery"],
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Lilac"],
    storageOptions: ["Standard"],
    stock: 41,
  },
  {
    id: "logitech-pop-keys",
    name: "Logitech Pop Keys",
    brand: "Logitech",
    category: "Accessories",
    price: 99,
    originalPrice: 129,
    discount: 23,
    rating: 4.5,
    reviewCount: 96,
    description: "A colorful wireless keyboard that adds personality and comfort to desktop workstations and creative setups.",
    features: ["Wireless Bluetooth", "Emoji keys", "Compact layout", "Multi-device support", "USB-C recharge"],
    images: [
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Lilac", "Aqua", "Peach"],
    storageOptions: ["Standard"],
    stock: 29,
  },
  {
    id: "asus-vivobook-15",
    name: "ASUS VivoBook 15",
    brand: "ASUS",
    category: "Laptops",
    price: 549,
    originalPrice: 649,
    discount: 15,
    rating: 4.5,
    reviewCount: 178,
    description: "A budget-friendly laptop for everyday computing, studying, and light creative work with good battery life.",
    features: ["15.6-inch FHD display", "AMD Ryzen 5", "8GB RAM", "512GB SSD", "Long battery"],
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Silver", "Black"],
    storageOptions: ["256GB", "512GB"],
    stock: 31,
  },
  {
    id: "samsung-galaxy-s24-ultra",
    name: "Samsung Galaxy S24 Ultra",
    brand: "Samsung",
    category: "Smartphones",
    price: 1299,
    originalPrice: 1499,
    discount: 13,
    rating: 4.9,
    reviewCount: 298,
    description: "The ultimate flagship with a professional S Pen, advanced AI camera, and premium build quality for power users.",
    features: ["6.8-inch Dynamic AMOLED", "Snapdragon 8 Gen 3", "200MP main camera", "S Pen included", "Titanium frame"],
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Titanium Black", "Titanium Gold", "Titanium Silver"],
    storageOptions: ["256GB", "512GB", "1TB"],
    stock: 13,
    badge: "Premium",
  },
  {
    id: "moto-g84",
    name: "Motorola Moto G84",
    brand: "Motorola",
    category: "Smartphones",
    price: 399,
    originalPrice: 479,
    discount: 17,
    rating: 4.4,
    reviewCount: 142,
    description: "A dependable mid-range phone with clean Android, great durability, and solid everyday performance.",
    features: ["6.5-inch AMOLED", "MediaTek Helio G99", "12GB RAM", "128GB storage", "50MP camera"],
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "White"],
    storageOptions: ["128GB"],
    stock: 38,
  },
  {
    id: "oppo-find-x7",
    name: "OPPO Find X7",
    brand: "OPPO",
    category: "Smartphones",
    price: 749,
    originalPrice: 899,
    discount: 17,
    rating: 4.6,
    reviewCount: 167,
    description: "A sleek design with flagship photography capabilities and smooth performance for creative users.",
    features: ["6.78-inch AMOLED", "Snapdragon 8 Gen 3", "Hasselblad camera", "120W charging", "IP69 rated"],
    images: [
      "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1671107965015-0f547e8e1fe3?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Purple"],
    storageOptions: ["256GB", "512GB"],
    stock: 20,
  },
  {
    id: "ipad-mini-7",
    name: "iPad Mini 7",
    brand: "Apple",
    category: "Tablets",
    price: 499,
    originalPrice: 599,
    discount: 17,
    rating: 4.7,
    reviewCount: 213,
    description: "Compact tablet with surprising power, perfect for reading, sketching, and portable creativity.",
    features: ["8.3-inch Liquid Retina", "A17 Pro chip", "Apple Pencil support", "USB-C", "12MP camera"],
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1452784444945-3f883f4d2ec7?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Space Gray", "Purple", "Starlight"],
    storageOptions: ["64GB", "256GB"],
    stock: 24,
  },
  {
    id: "oneplus-pad",
    name: "OnePlus Pad",
    brand: "OnePlus",
    category: "Tablets",
    price: 379,
    originalPrice: 479,
    discount: 21,
    rating: 4.5,
    reviewCount: 134,
    description: "A smooth 120Hz tablet experience with fast performance and competitive pricing for productivity and entertainment.",
    features: ["11.6-inch 144Hz LCD", "Snapdragon 8 Gen 1", "8GB RAM", "128GB storage", "Stylus support"],
    images: [
      "https://images.unsplash.com/photo-1589739900243-4b5d7d7a9d90?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512054502232-10a0a035d672?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Halo Gray", "Moonstone Gray"],
    storageOptions: ["128GB", "256GB"],
    stock: 21,
  },
  {
    id: "samsung-galaxy-buds-3",
    name: "Samsung Galaxy Buds 3",
    brand: "Samsung",
    category: "Accessories",
    price: 179,
    originalPrice: 229,
    discount: 22,
    rating: 4.7,
    reviewCount: 245,
    description: "Wireless earbuds with active noise cancellation, seamless Galaxy integration, and balanced sound quality.",
    features: ["Active noise cancellation", "IPX7 waterproof", "33-hour battery", "Touch controls", "Wireless charging case"],
    images: [
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["White", "Black"],
    storageOptions: ["Standard"],
    stock: 39,
  },
  {
    id: "anker-power-bank-737",
    name: "Anker 737 Power Bank",
    brand: "Anker",
    category: "Accessories",
    price: 49,
    originalPrice: 69,
    discount: 29,
    rating: 4.8,
    reviewCount: 312,
    description: "A high-capacity fast-charging power bank with multiple ports for charging multiple devices simultaneously.",
    features: ["40,000mAh capacity", "140W output", "Multi-port support", "Compact design", "LED display"],
    images: [
      "https://images.unsplash.com/photo-1591290621749-1a3b15dbdd8e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "White"],
    storageOptions: ["Standard"],
    stock: 56,
    badge: "Bestseller",
  },
  {
    id: "sennheiser-momentum-3",
    name: "Sennheiser Momentum 3",
    brand: "Sennheiser",
    category: "Accessories",
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.8,
    reviewCount: 216,
    description: "Premium over-ear headphones with exceptional sound quality, comfort, and build durability for audiophiles.",
    features: ["40-hour battery", "Transparent mode", "Touch controls", "Premium materials", "Wireless + 3.5mm"],
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "White"],
    storageOptions: ["Standard"],
    stock: 18,
  },
  {
    id: "corsair-k95-platinum-xt",
    name: "Corsair K95 Platinum XT",
    brand: "Corsair",
    category: "Accessories",
    price: 229,
    originalPrice: 279,
    discount: 18,
    rating: 4.7,
    reviewCount: 189,
    description: "A premium mechanical gaming keyboard with customizable RGB lighting and exceptional build quality.",
    features: ["Cherry MX switches", "RGB lighting", "Aluminum frame", "USB-C", "Macro programming"],
    images: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Black/Silver"],
    storageOptions: ["Standard"],
    stock: 22,
  },
  {
    id: "elgato-stream-deck",
    name: "Elgato Stream Deck XL",
    brand: "Elgato",
    category: "Accessories",
    price: 249,
    originalPrice: 299,
    discount: 17,
    rating: 4.9,
    reviewCount: 276,
    description: "A control center for content creators with customizable buttons for streaming, gaming, and productivity.",
    features: ["32 programmable keys", "Customizable LCDs", "4K streaming support", "USB connectivity", "Software integration"],
    images: [
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black"],
    storageOptions: ["Standard"],
    stock: 19,
  },
  {
    id: "huawei-watch-gt5",
    name: "Huawei Watch GT 5",
    brand: "Huawei",
    category: "Smartwatches",
    price: 249,
    originalPrice: 319,
    discount: 22,
    rating: 4.6,
    reviewCount: 142,
    description: "A feature-rich smartwatch with excellent battery life, health tracking, and a premium design aesthetic.",
    features: ["AMOLED display", "2-week battery", "All-day blood oxygen", "100+ sports modes", "Water resistant"],
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Gold"],
    storageOptions: ["42mm", "46mm"],
    stock: 27,
  },
  {
    id: "withings-scanwatch",
    name: "Withings ScanWatch",
    brand: "Withings",
    category: "Smartwatches",
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.7,
    reviewCount: 198,
    description: "A medical-grade smartwatch with ECG and SpO2 monitoring, perfect for health-conscious users.",
    features: ["ECG monitoring", "SpO2 tracking", "30-day battery", "Hybrid display", "Sleep analysis"],
    images: [
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["White", "Black"],
    storageOptions: ["42mm", "38mm"],
    stock: 14,
  },
  {
    id: "amazfit-gtr-4",
    name: "Amazfit GTR 4",
    brand: "Amazfit",
    category: "Smartwatches",
    price: 179,
    originalPrice: 239,
    discount: 25,
    rating: 4.6,
    reviewCount: 174,
    description: "A value-packed smartwatch with detailed fitness tracking, long battery life, and crisp display.",
    features: ["150+ sports modes", "14-day battery", "Always-on display", "Health tracking", "GPS built-in"],
    images: [
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Midnight Black", "Ocean Blue"],
    storageOptions: ["47mm", "41mm"],
    stock: 33,
    badge: "Value Pick",
  },
  {
    id: "soundcore-liberty-4",
    name: "Soundcore Liberty 4",
    brand: "Soundcore",
    category: "Accessories",
    price: 89,
    originalPrice: 129,
    discount: 31,
    rating: 4.6,
    reviewCount: 287,
    description: "Budget-friendly wireless earbuds with solid ANC, clear sound, and long battery life for daily use.",
    features: ["Active noise cancellation", "11-hour playtime", "IPX5 waterproof", "LDAC support", "Quick charge"],
    images: [
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "White"],
    storageOptions: ["Standard"],
    stock: 44,
  },
  {
    id: "apple-magic-keyboard",
    name: "Apple Magic Keyboard",
    brand: "Apple",
    category: "Accessories",
    price: 149,
    originalPrice: 179,
    discount: 17,
    rating: 4.7,
    reviewCount: 223,
    description: "A wireless keyboard with sleek design, rechargeable battery, and seamless Apple ecosystem integration.",
    features: ["Wireless Bluetooth", "Rechargeable battery", "Numeric keypad", "Aluminum design", "Multi-device support"],
    images: [
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Silver", "Black"],
    storageOptions: ["Standard"],
    stock: 31,
  },
  {
    id: "gigabyte-gaming-monitor-27",
    name: "Gigabyte Aorus G27QF",
    brand: "Gigabyte",
    category: "Accessories",
    price: 349,
    originalPrice: 449,
    discount: 22,
    rating: 4.8,
    reviewCount: 198,
    description: "A 27-inch 1440p gaming monitor with 240Hz refresh rate and HDR support for competitive gaming and design work.",
    features: ["27-inch QHD display", "240Hz refresh", "1ms response", "HDR support", "DisplayPort + HDMI"],
    images: [
      "https://images.unsplash.com/photo-1599298760730-f51ee931e991?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black"],
    storageOptions: ["Standard"],
    stock: 16,
  },
  {
    id: "victus-laptop-16",
    name: "HP Victus 16",
    brand: "HP",
    category: "Laptops",
    price: 1299,
    originalPrice: 1599,
    discount: 19,
    rating: 4.7,
    reviewCount: 176,
    description: "A powerful gaming laptop built for high-end gaming and content creation with a large immersive display.",
    features: ["16-inch FHD display", "RTX 4070", "32GB RAM", "1TB SSD", "144Hz refresh"],
    images: [
      "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Gray"],
    storageOptions: ["512GB", "1TB"],
    stock: 12,
  },
  {
    id: "macbook-pro-16-m3-max",
    name: "MacBook Pro 16 M3 Max",
    brand: "Apple",
    category: "Laptops",
    price: 3499,
    originalPrice: 3999,
    discount: 13,
    rating: 4.9,
    reviewCount: 287,
    description: "The ultimate professional laptop with unparalleled performance for video editing, 3D rendering, and software development.",
    features: ["16-inch Liquid Retina XDR", "M3 Max chip", "36GB unified memory", "1TB SSD", "ProMotion 120Hz"],
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Silver", "Space Black"],
    storageOptions: ["512GB", "1TB", "2TB"],
    stock: 7,
    badge: "Premium Pro",
  },
  {
    id: "samsung-galaxy-z-flip-6",
    name: "Samsung Galaxy Z Flip 6",
    brand: "Samsung",
    category: "Smartphones",
    price: 999,
    originalPrice: 1149,
    discount: 13,
    rating: 4.7,
    reviewCount: 195,
    description: "A compact foldable that folds to pocket size with premium design, vibrant display, and excellent cameras.",
    features: ["6.7-inch main + 3.4-inch cover", "Snapdragon 8 Gen 3", "12GB RAM", "Dual cameras", "Compact fold"],
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Silver Shadow", "Blue"],
    storageOptions: ["256GB", "512GB"],
    stock: 14,
  },
];

export const categoryMap: Record<string, string> = {
  laptops: "Laptops",
  smartphones: "Smartphones",
  tablets: "Tablets",
  accessories: "Accessories",
  smartwatches: "Smartwatches",
};

export function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}

export function getProductsByCategory(categorySlug: string) {
  const categoryName = categoryMap[categorySlug];
  if (!categoryName) return [] as Product[];
  return products.filter((product) => product.category === categoryName);
}

export function getProductById(id: string) {
  return products.find((product) => product.id === id);
}
