export type CategoryName = "Laptops" | "Smartphones" | "Tablets" | "Accessories" | "Smartwatches";

export type Product = {
  id: string;
  name: string;
  brand: string;
  category: CategoryName;
  price: number;
  originalPrice: number;
  discount: number;
  rating: number;
  reviewCount: number;
  description: string;
  features: string[];
  images: string[];
  colors: string[];
  storageOptions: string[];
  stock: number;
  badge?: string;
};

export const categories: { name: CategoryName; slug: string; description: string; count: number }[] = [
  { name: "Laptops", slug: "laptops", description: "Premium laptops for work, study, and play.", count: 7 },
  { name: "Smartphones", slug: "smartphones", description: "Latest smartphones with cutting-edge performance.", count: 5 },
  { name: "Tablets", slug: "tablets", description: "Portable power for creativity and entertainment.", count: 3 },
  { name: "Accessories", slug: "accessories", description: "Boost your setup with modern essentials.", count: 4 },
  { name: "Smartwatches", slug: "smartwatches", description: "Track fitness and stay connected on the go.", count: 3 },
];

export const products: Product[] = [
  {
    id: "macbook-air-m2",
    name: "MacBook Air M2",
    brand: "Apple",
    category: "Laptops",
    price: 1199,
    originalPrice: 1399,
    discount: 14,
    rating: 4.9,
    reviewCount: 321,
    description: "Ultra-lightweight laptop with an all-day battery, stunning Retina display, and the performance to handle productivity, creativity, and entertainment effortlessly.",
    features: ["13.6-inch Liquid Retina display", "Apple M2 chip", "Up to 18 hours battery life", "Fanless design", "Backlit keyboard"],
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Silver", "Midnight", "Starlight", "Space Gray"],
    storageOptions: ["256GB", "512GB", "1TB"],
    stock: 18,
    badge: "Best Seller",
  },
  {
    id: "dell-xps-13",
    name: "Dell XPS 13",
    brand: "Dell",
    category: "Laptops",
    price: 999,
    originalPrice: 1199,
    discount: 17,
    rating: 4.8,
    reviewCount: 244,
    description: "A premium ultrabook with a near-borderless InfinityEdge display and cutting-edge Intel performance for work and travel.",
    features: ["13.4-inch FHD+ display", "Intel Core i7", "16GB RAM", "512GB SSD", "Windows 11 Pro"],
    images: [
      "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1504703395950-b89145a5425b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Platinum Silver", "Black"],
    storageOptions: ["512GB", "1TB"],
    stock: 14,
  },
  {
    id: "hp-spectre-x360",
    name: "HP Spectre x360",
    brand: "HP",
    category: "Laptops",
    price: 1099,
    originalPrice: 1299,
    discount: 15,
    rating: 4.7,
    reviewCount: 193,
    description: "Convertible premium laptop that effortlessly transitions between laptop, tablet, and creative workstation modes.",
    features: ["14-inch 2.8K OLED", "Intel Evo Platform", "16GB RAM", "1TB SSD", "360° hinge"],
    images: [
      "https://images.unsplash.com/photo-1551808525-51a94da548ce?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Nightfall Black", "Poseidon Blue"],
    storageOptions: ["512GB", "1TB"],
    stock: 20,
  },
  {
    id: "asus-zenbook-14",
    name: "ASUS ZenBook 14",
    brand: "ASUS",
    category: "Laptops",
    price: 949,
    originalPrice: 1099,
    discount: 14,
    rating: 4.6,
    reviewCount: 162,
    description: "Sleek ultrabook with a compact footprint and strong everyday performance for professionals and students.",
    features: ["14-inch OLED display", "AMD Ryzen 7", "16GB RAM", "1TB SSD", "USB-C fast charge"],
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1541534401786-2077eed87a74?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Ponder Blue", "Gray"],
    storageOptions: ["512GB", "1TB"],
    stock: 26,
  },
  {
    id: "lenovo-thinkpad-x1",
    name: "Lenovo ThinkPad X1",
    brand: "Lenovo",
    category: "Laptops",
    price: 1349,
    originalPrice: 1549,
    discount: 13,
    rating: 4.7,
    reviewCount: 130,
    description: "Built for business productivity with legendary keyboard comfort, enterprise-grade durability, and secure performance.",
    features: ["14-inch UHD display", "Intel Core i7", "32GB RAM", "1TB SSD", "ThinkShield security"],
    images: [
      "https://images.unsplash.com/photo-1521543381607-4fddd1d76c8b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Graphite"],
    storageOptions: ["512GB", "1TB"],
    stock: 11,
  },
  {
    id: "msi-gaming-laptop",
    name: "MSI Raider GE78",
    brand: "MSI",
    category: "Laptops",
    price: 1699,
    originalPrice: 1999,
    discount: 15,
    rating: 4.8,
    reviewCount: 188,
    description: "Performance-first gaming laptop with high-refresh display, advanced cooling, and immersive visuals for serious players.",
    features: ["17.3-inch QHD+ display", "RTX 4080", "32GB RAM", "2TB SSD", "144Hz refresh"],
    images: [
      "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Titanium"],
    storageOptions: ["1TB", "2TB"],
    stock: 9,
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    brand: "Apple",
    category: "Smartphones",
    price: 999,
    originalPrice: 1099,
    discount: 9,
    rating: 4.9,
    reviewCount: 431,
    description: "A titanium-framed flagship with exceptional camera power, a blazing-fast chip, and all-day performance.",
    features: ["6.1-inch Super Retina XDR", "A17 Pro chip", "Pro camera system", "USB-C connectivity", "Dynamic Island"],
    images: [
      "https://images.unsplash.com/photo-1671107965015-0f547e8e1fe3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1539185441755-769473a23570?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Natural Titanium", "Blue Titanium", "White Titanium"],
    storageOptions: ["128GB", "256GB", "512GB", "1TB"],
    stock: 35,
    badge: "Hot Deal",
  },
  {
    id: "samsung-galaxy-s24",
    name: "Samsung Galaxy S24",
    brand: "Samsung",
    category: "Smartphones",
    price: 829,
    originalPrice: 949,
    discount: 13,
    rating: 4.8,
    reviewCount: 275,
    description: "A powerful AI-enhanced smartphone with a brilliant display and versatile camera system built for every day.",
    features: ["6.2-inch AMOLED display", "Snapdragon 8 Gen 3", "50MP camera", "AI tools", "Fast wireless charging"],
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Onyx Black", "Marble Gray", "Violet"],
    storageOptions: ["128GB", "256GB", "512GB"],
    stock: 42,
  },
  {
    id: "oneplus-12",
    name: "OnePlus 12",
    brand: "OnePlus",
    category: "Smartphones",
    price: 799,
    originalPrice: 899,
    discount: 11,
    rating: 4.7,
    reviewCount: 214,
    description: "A smooth and fast flagship with flagship-level cameras, immersive visuals, and fluid performance.",
    features: ["6.8-inch AMOLED display", "Snapdragon 8 Gen 3", "120Hz refresh rate", "Triple camera system", "Ultra-fast charging"],
    images: [
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1556656793-08538906a9f8?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Fluorite Black", "Flowing Silver"],
    storageOptions: ["256GB", "512GB"],
    stock: 29,
  },
  {
    id: "google-pixel-9",
    name: "Google Pixel 9",
    brand: "Google",
    category: "Smartphones",
    price: 749,
    originalPrice: 899,
    discount: 17,
    rating: 4.6,
    reviewCount: 183,
    description: "Built around AI photography and seamless Android integration, designed to make everyday moments feel effortless.",
    features: ["6.3-inch display", "Tensor G4", "Advanced AI camera", "7 years updates", "Wireless charging"],
    images: [
      "https://images.unsplash.com/photo-1601784551446-20c9e07d2c4e?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1521311863870-7e1b10d6bf0c?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Obsidian", "Porcelain"],
    storageOptions: ["128GB", "256GB"],
    stock: 32,
  },
  {
    id: "nothing-phone-2",
    name: "Nothing Phone 2",
    brand: "Nothing",
    category: "Smartphones",
    price: 699,
    originalPrice: 799,
    discount: 13,
    rating: 4.5,
    reviewCount: 121,
    description: "A distinctive design and clean Android experience with sustainable materials and good everyday performance.",
    features: ["6.7-inch AMOLED", "Glyph interface", "Dual rear cameras", "Snapdragon 8+ Gen 1", "Fast charging"],
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["White", "Black"],
    storageOptions: ["128GB", "256GB"],
    stock: 25,
  },
  {
    id: "ipad-air",
    name: "iPad Air",
    brand: "Apple",
    category: "Tablets",
    price: 599,
    originalPrice: 699,
    discount: 14,
    rating: 4.8,
    reviewCount: 270,
    description: "An ultra-portable tablet that combines an immersive display with all-day battery life and powerful creative tools.",
    features: ["10.9-inch Liquid Retina display", "M2 chip", "Apple Pencil support", "Touch ID", "USB-C"],
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1452784444945-3f883f4d2ec7?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Space Gray", "Blue", "Purple"],
    storageOptions: ["64GB", "256GB"],
    stock: 19,
  },
  {
    id: "samsung-galaxy-tab-s9",
    name: "Samsung Galaxy Tab S9",
    brand: "Samsung",
    category: "Tablets",
    price: 649,
    originalPrice: 749,
    discount: 13,
    rating: 4.7,
    reviewCount: 149,
    description: "Premium Android tablet with an immersive AMOLED display and strong productivity features for work and creativity.",
    features: ["11-inch AMOLED", "Qualcomm Snapdragon", "S Pen included", "Dual speakers", "Long battery life"],
    images: [
      "https://images.unsplash.com/photo-1589739900243-4b5d7d7a9d90?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512054502232-10a0a035d672?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Beige", "Graphite"],
    storageOptions: ["128GB", "256GB"],
    stock: 17,
  },
  {
    id: "microsoft-surface-go-4",
    name: "Microsoft Surface Go 4",
    brand: "Microsoft",
    category: "Tablets",
    price: 499,
    originalPrice: 599,
    discount: 17,
    rating: 4.4,
    reviewCount: 92,
    description: "Portable and lightweight 2-in-1 tablet with flexible productivity features for students and on-the-go creators.",
    features: ["10.5-inch touchscreen", "Intel processor", "Windows 11", "Portable design", "Keyboard compatible"],
    images: [
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1525547719571-a2d4ac8945e2?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Platinum", "Black"],
    storageOptions: ["64GB", "128GB"],
    stock: 21,
  },
  {
    id: "airpods-pro",
    name: "AirPods Pro",
    brand: "Apple",
    category: "Accessories",
    price: 249,
    originalPrice: 299,
    discount: 17,
    rating: 4.9,
    reviewCount: 512,
    description: "Wireless earbuds with adaptive audio, active noise cancellation, and a comfortable, secure fit for all-day listening.",
    features: ["Active noise cancellation", "Adaptive audio", "USB-C charging case", "Spatial audio", "Sweat and water resistant"],
    images: [
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["White", "Black"],
    storageOptions: ["Standard"],
    stock: 48,
    badge: "Top Rated",
  },
  {
    id: "logitech-mx-master-3",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "Accessories",
    price: 99,
    originalPrice: 129,
    discount: 23,
    rating: 4.8,
    reviewCount: 359,
    description: "A premium wireless mouse for creators and professionals with exceptional precision, smooth scrolling, and multi-device control.",
    features: ["Ultra-fast scroll", "Multi-device pairing", "Quiet clicks", "Ergonomic shape", "USB-C charging"],
    images: [
      "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Graphite", "Black"],
    storageOptions: ["Standard"],
    stock: 52,
  },
  {
    id: "sony-wh-1000xm5",
    name: "Sony WH-1000XM5",
    brand: "Sony",
    category: "Accessories",
    price: 379,
    originalPrice: 449,
    discount: 16,
    rating: 4.9,
    reviewCount: 286,
    description: "Premium noise-canceling headphones tuned for crisp audio, travel comfort, and immersive listening.",
    features: ["Industry-leading ANC", "30-hour battery", "Quick charge", "Ambient sound control", "Bluetooth multipoint"],
    images: [
      "https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Silver"],
    storageOptions: ["Standard"],
    stock: 23,
  },
  {
    id: "belkin-usb-c-hub",
    name: "Belkin USB-C Hub",
    brand: "Belkin",
    category: "Accessories",
    price: 89,
    originalPrice: 109,
    discount: 18,
    rating: 4.6,
    reviewCount: 98,
    description: "Expand your laptop connectivity with a compact USB-C hub offering power, HDMI, and multiple USB ports.",
    features: ["4K HDMI output", "Multiple USB-A ports", "Power delivery", "Compact design", "Plug-and-play"],
    images: [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1552581234-26160f608093?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Gray"],
    storageOptions: ["Standard"],
    stock: 37,
  },
  {
    id: "apple-watch-series-9",
    name: "Apple Watch Series 9",
    brand: "Apple",
    category: "Smartwatches",
    price: 399,
    originalPrice: 499,
    discount: 20,
    rating: 4.8,
    reviewCount: 332,
    description: "A powerful smartwatch with health insights, faster performance, and all-day battery to keep up with your routine.",
    features: ["Always-On Retina display", "GPS + Cellular", "Advanced health tracking", "Water resistant", "Fast charging"],
    images: [
      "https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Midnight", "Starlight", "Silver"],
    storageOptions: ["41mm", "45mm"],
    stock: 40,
  },
  {
    id: "garmin-forerunner-265",
    name: "Garmin Forerunner 265",
    brand: "Garmin",
    category: "Smartwatches",
    price: 329,
    originalPrice: 399,
    discount: 18,
    rating: 4.7,
    reviewCount: 171,
    description: "Designed for runners and active lifestyles, bringing a bright display and detailed training insights to your wrist.",
    features: ["GPS + HRM", "Training readiness", "Long battery life", " AMOLED display", "Body battery"],
    images: [
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Black", "Gray", "Blue"],
    storageOptions: ["42mm", "46mm"],
    stock: 34,
  },
  {
    id: "samsung-galaxy-watch-6",
    name: "Samsung Galaxy Watch 6",
    brand: "Samsung",
    category: "Smartwatches",
    price: 299,
    originalPrice: 349,
    discount: 14,
    rating: 4.6,
    reviewCount: 157,
    description: "A versatile smartwatch with smart health tracking, intuitive gestures, and a slim, premium design.",
    features: ["Advanced sleep tracking", "Body composition analysis", "Bluetooth + LTE", "Super AMOLED", "Water resistant"],
    images: [
      "https://images.unsplash.com/photo-1617043786394-f977fa12eddf?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Graphite", "Silver"],
    storageOptions: ["40mm", "44mm"],
    stock: 29,
  },
  {
    id: "asus-rog-phone-8",
    name: "ASUS ROG Phone 8",
    brand: "ASUS",
    category: "Smartphones",
    price: 899,
    originalPrice: 999,
    discount: 10,
    rating: 4.7,
    reviewCount: 129,
    description: "A gamer-focused flagship with a high-refresh display, exceptional airflow, and performance tuned for competitive play.",
    features: ["6.78-inch AMOLED", "Snapdragon 8 Gen 3", "AeroActive cooling", "Dual front speakers", "Game controls"],
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Phantom Black", "Storm White"],
    storageOptions: ["256GB", "512GB"],
    stock: 18,
  },
  {
    id: "apple-mac-mini-m4",
    name: "Apple Mac mini M4",
    brand: "Apple",
    category: "Accessories",
    price: 699,
    originalPrice: 799,
    discount: 13,
    rating: 4.7,
    reviewCount: 135,
    description: "An efficient desktop mini-PC built for home offices, creative workflows, and compact setups that still demand power.",
    features: ["Compact desktop form", "M4 chip", "Thunderbolt ports", "Wi-Fi 6E", "Energy efficient"],
    images: [
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    ],
    colors: ["Silver", "Space Gray"],
    storageOptions: ["256GB", "512GB"],
    stock: 16,
  },

];

export const categoryMap: Record<string, string> = {
  laptops: "Laptops",
  smartphones: "Smartphones",
  tablets: "Tablets",
  accessories: "Accessories",
  smartwatches: "Smartwatches",
};

export function formatCurrency(value: number) {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}

export function getProductsByCategory(categorySlug: string) {
  const categoryName = categoryMap[categorySlug];
  if (!categoryName) return [] as Product[];
  return products.filter((product) => product.category === categoryName);
}

export function getProductById(id: string) {
  return products.find((product) => product.id === id);
}
